project:
  type: website

website:
  title: "Epinowcast"
  site-url: https://epinowcast.org
  description: "Epinowcast community site"
  twitter-card:
    creator: "@seabbs"
    site: "@epinowcast"
  favicon: images/favicon-32x32.png
  open-graph: true
  comments:
    giscus:
      repo: epinowcast/epinowcast.github.io
      category: 'Website discussions'
      mapping: title
      reactions-enabled: true
  navbar:
    left:
      - text: "Package"
        href: "https://package.epinowcast.org"
      - text: "Community"
        href: "https://community.epinowcast.org"
      - text: "Blog"
        href: blog.qmd
      - text: "Help"
        href: help.qmd
      - text: "Contribute"
        href: contribute.qmd
      - text: "Funding"
        href: funding.qmd
    right:
      - icon: github
        href: https://github.com/epinowcast/epinowcast.github.io

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
