---
title: "Kaitlyn Johnson - Baseline nowcasting methods for handling delays in epidemiological data" 
date: 2025-09-03
comments: false
---

On Wednesday September 3rd, Kaitlyn Johnson will discuss baseline methods for nowcasting and its applications. This work has recently been posted as a [pre-print](https://www.medrxiv.org/content/10.1101/2025.08.14.25333653v1). 

Reporting delays in public health surveillance systems can create a misleading impression of declining trends in recent data. While a number of “nowcasting” methods have been developed to correct this bias, widespread adoption in public health practice has yet to be realized. Currently, there is no simple method to perform nowcasting that both meets the needs of public health practice and can be used as a benchmark for further methodological advancement. In this work, we present a family of baseline nowcasting methods, and an accompanying software package, [baselinenowcast](https://github.com/epinowcast/baselinenowcast), designed specifically to address these two gaps. We evaluate the performance of the default method against other methods used in previous studies and assess the performance of different method specifications. Our findings indicate that our baseline methods improve performance over unadjusted data or more ad-hoc baseline nowcasting approaches, provide an interpretable and accessible nowcasting solution for public health practice, and are useful as a standard benchmark for more advanced methods. 

Kaitlyn is currently an Assistant Professor at the London School of Hygiene and Tropical Medicine working in Sebastian Funk's Epiforecasts group. Prior to joining, she worked as a data scientist at the U.S. CDC's Center for Forecasting and Outbreak Analytics. Her broader interests include: real-time outbreak analysis, open source tool development, wastewater-based epidemiology, partial pooling/hierarchical modeling, integration of complex and disparate data sources.

A recording of this talk will be posted to our [YouTube channel](https://www.youtube.com/channel/UC9qvwwGTudtKnOE-sM1LooQ) and asynchronous discussion will be possible on [our community site](https://community.epinowcast.org/c/meetings/8). You can also ask questions ahead of time and asynchronously there.

## Connect to seminars

You can sign up for our event calendar here: [Google calendar ](https://calendar.google.com/calendar/u/0/r?cid=YTExM2I2ZjVkOTYxODA4ZjA5YjdhODA3ZTIwMzU1Mzk4ODY0Y2NhYjIzOWVkNjAyYzc5ZTkzYWM5OWY0YWQxM0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Or here for non-Google calendar users: [ICAL link ](https://calendar.google.com/calendar/ical/a113b6f5d961808f09b7a807e20355398864ccab239ed602c79e93ac99f4ad13%40group.calendar.google.com/public/basic.ics)

Or just join seminars directly here: [https://lshtm.zoom.us/j/8290218109 ](https://lshtm.zoom.us/j/8290218109)

To get an email with details of community meetings you can sign up to our community forum and watch (using the bell on the top right) the [Meeting category](https://community.epinowcast.org/c/meetings/8).

More details about this seminar series are available [here](../../seminars.qmd).
